/* Plugin Template generated by Pawn Studio */
#pragma semicolon 1
#pragma newdecls required
#include <sourcemod>
#include <config>
#include <sdkhooks>
#include <sdktools>
#include <collisionhook>

#define MODEL_NONE			 "none"
#define PLUGIN_VERSION		 "2.4"

#define TEAM_INFECTED		 3
#define TEAM_SURVIVOR		 2

#define ZC_SMOKER			 1
#define ZC_BOOMER			 2
#define ZC_HUNTER			 3
#define ZC_SPITTER			 4
#define ZC_JOCKEY			 5
#define ZC_CHARGER			 6
#define ZC_WITCH			 7
#define ZC_TANK				 8
#define ZC_NOTINFECTED		 9

#define FACTORYNAME_ITEM	 "item"
#define FACTORYNAME_WEAPON	 "weapon"
#define FACTORYNAME_UPGRADE	 "upgrade"
#define FACTORYNAME_MELEE	 "melee"
#define FACTORYNAME_INFECTED "infected"
#define FACTORYNAME_EXPLODE	 "explode"

public Plugin myinfo =
{
	name		= "[L4D2] Infected Loot Drops",
	author		= "Thraka, BloodyBlade, apples1949",
	description = "Randomly (or not) generate items or infected to spawn when an infected dies.And fix any bug",
	version		= PLUGIN_VERSION,
	url			= "http://forums.alliedmods.net/showthread.php?p=1099583#"


}

// Globals
Handle g_hConfig	= null,
	   g_hMaxSpawns = null, g_hMaxSpawnsCounters = null;
bool	  g_bWriteLog = false, g_bPluginOn = true;
ConVar	  CVAR_loot_cfg, CVAR_loot_enabled, CVAR_loot_log_enabled, CVAR_loot_announce_mode;
bool	  g_bSpawnUncommonSupported = false;
int		  g_iAnnounceMode			= 0;
ArrayList g_PropaneTanks;

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
	EngineVersion engine = GetEngineVersion();
	if (engine != Engine_Left4Dead2)
	{
		strcopy(error, err_max, "This plugin only runs in \"Left 4 Dead 2\" game");
		return APLRes_SilentFailure;
	}
	return APLRes_Success;
}

public void OnPluginStart()
{
	// Create and hook cvars
	CreateConVar("l4d2_loot_version", PLUGIN_VERSION, "Version of the infected loot drops plugins.", FCVAR_NOTIFY | FCVAR_SPONLY | FCVAR_DONTRECORD);
	CVAR_loot_cfg			= CreateConVar("l4d2_loot_config_filename", "loot/loot_default.conf", "The name of the config file located in the cfg-sourcemod folder.", FCVAR_NOTIFY);
	CVAR_loot_enabled		= CreateConVar("l4d2_loot_enabled", "1", "Is the infected loot plugin enabled or not.", FCVAR_NOTIFY);
	CVAR_loot_log_enabled	= CreateConVar("l4d2_loot_logging", "0", "Enable logging.", FCVAR_NOTIFY);
	CVAR_loot_announce_mode = CreateConVar("l4d2_loot_announce_mode", "1", "Announces text to client teams when something spawns (if defined) 0 = Off; 1 = Hint text; 2 = Team chat.", FCVAR_NOTIFY);

	CVAR_loot_enabled.AddChangeHook(CvarOnOffChanged);
	CVAR_loot_log_enabled.AddChangeHook(CvarLoggingChanged);
	CVAR_loot_cfg.AddChangeHook(CvarConfigFileChanged);
	CVAR_loot_announce_mode.AddChangeHook(CvarAnnounceModeChanged);

	g_bPluginOn		= GetConVarBool(CVAR_loot_enabled);
	g_bWriteLog		= GetConVarBool(CVAR_loot_log_enabled);
	g_iAnnounceMode = GetConVarInt(CVAR_loot_announce_mode);

	// Reg commands
	RegConsoleCmd("loot_reloadconfig", Command_ReloadConfig, "Reloads the current conf file specified by the l4d2_loot_config_filename cvar.", ADMFLAG_KICK);
	RegConsoleCmd("loot_sim", Command_SimInfected, "Simulates an infected killed, so you can see what would happen.", ADMFLAG_KICK);
	RegConsoleCmd("loot_get_thingcount", Command_GetThingCount, "Gets how many times a specific thing has spawned.", ADMFLAG_KICK);
	RegConsoleCmd("loot_add_thingcount", Command_AddThingCount, "Adds 1 to a specific thing count of how many times it's spawned.", ADMFLAG_KICK);
	RegConsoleCmd("loot_get_thingmax", Command_GetThingMax, "Gets the max spawn setting of a thing.", ADMFLAG_KICK);
	RegConsoleCmd("loot_thing_ismaxed", Command_IsThingMaxed, "Informs you of if a thing has already reached the max spawn limit.", ADMFLAG_KICK);

	// Enable these for testing if you want.
	// RegConsoleCmd("loot_give", Command_Give, "Executes the give command on the current client.");
	// RegConsoleCmd("loot_spawn", Command_Spawn, "Executes the z_spawn command.");

	HookEvent("player_death", Event_PlayerDeath);
	HookEvent("round_start", Event_RoundStart);

	// Auto config
	AutoExecConfig(true, "l4d2_infected_loot_drops");

	LoadConfig();

	g_PropaneTanks = new ArrayList();
}

public void OnPluginEnd()
{
	CloseHandle(g_hConfig);
	g_hConfig = null;
	delete g_PropaneTanks;
}

public void OnMapStart()
{
	// Precache uncommon infected models
	PrecacheModel("models/infected/common_male_riot.mdl", true);
	PrecacheModel("models/infected/common_male_ceda.mdl", true);
	PrecacheModel("models/infected/common_male_clown.mdl", true);
	PrecacheModel("models/infected/common_male_mud.mdl", true);
	PrecacheModel("models/infected/common_male_roadcrew.mdl", true);
	PrecacheModel("models/infected/common_male_jimmy.mdl", true);
	PrecacheModel("models/infected/common_male_fallen_survivor.mdl", true);

	// Precache the other weapons
	PrecacheModel("models/v_models/v_rif_sg552.mdl", true);
	PrecacheModel("models/w_models/weapons/w_rifle_sg552.mdl", true);
	PrecacheModel("models/v_models/v_snip_awp.mdl", true);
	PrecacheModel("models/w_models/weapons/w_sniper_awp.mdl", true);
	PrecacheModel("models/v_models/v_snip_scout.mdl", true);
	PrecacheModel("models/w_models/weapons/w_sniper_scout.mdl", true);
	PrecacheModel("models/v_models/v_smg_mp5.mdl", true);
	PrecacheModel("models/w_models/weapons/w_smg_mp5.mdl", true);
	PrecacheModel("models/w_models/weapons/50cal.mdl", true);

	LoadConfig();

	// Configure uncommon support
	g_bSpawnUncommonSupported = FindConVar("l4d2_spawn_uncommons_version") != null;
}

public void OnMapEnd()
{
	g_PropaneTanks.Clear();
}

///////////////////
// Commands
///////////////////
Action Command_SimInfected(int client, int args)
{
	char  arg[128];
	float location[3];

	if (args == 1 && client != 0)
	{
		GetCmdArg(1, arg, sizeof(arg));
		GetClientAbsOrigin(client, location);
		InfectedKilled(arg, true, location);
	}
	else if (client == 0)
	{
		GetCmdArg(1, arg, sizeof(arg));
		InfectedKilled(arg, true, location);
	}
	else
	{
		ReplyToCommand(client, "Format: loot_sim classname.");
		ReplyToCommand(client, "For example:");
		ReplyToCommand(client, "loot_sim smoker");
		ReplyToCommand(client, "loot_sim tank");
		ReplyToCommand(client, "loot_sim global");
	}
	return Plugin_Handled;
}

/*Action Command_Give(int client, int args)
{
	if (args == 1 && client != 0)
	{
		char arg[128];
		GetCmdArg(1, arg, sizeof(arg));
		GiveItem(client, arg);
	}
	else
		ReplyToCommand(client, "Format: sm_give itemname");

	return Plugin_Handled;
}*/

Action Command_ReloadConfig(int client, int args)
{
	ReplyToCommand(client, "Loading config...");
	LoadConfig();
	return Plugin_Handled;
}

/*Action Command_Spawn(int client, int args)
{
	if (args == 1 && client != 0)
	{
		char arg[128];
		GetCmdArg(1, arg, sizeof(arg));

		int flags = GetCommandFlags("z_spawn");
		SetCommandFlags("z_spawn", flags & ~FCVAR_CHEAT);
		FakeClientCommand(GetAnyClient(), "z_spawn %s", arg);
		SetCommandFlags("z_spawn", flags);
	}
	else
		ReplyToCommand(client, "Format: sm_spawn classname");

	return Plugin_Handled;
}*/

Action Command_GetThingCount(int client, int args)
{
	if (args == 2)
	{
		char type[128], name[128];
		GetCmdArg(1, type, sizeof(type));
		GetCmdArg(2, name, sizeof(name));

		ReplyToCommand(client, "Count: %i", GetThingCount(name, type));
	}
	else
	{
		ReplyToCommand(client, "Format: loot_get_thingcount [type] [name]");
		ReplyToCommand(client, "Example: loot_get_thingcount weapon weapon_smg");
	}
	return Plugin_Handled;
}

Action Command_AddThingCount(int client, int args)
{
	if (args == 3)
	{
		char type[85], name[85], count[85];
		GetCmdArg(1, type, sizeof(type));
		GetCmdArg(2, name, sizeof(name));
		GetCmdArg(3, count, sizeof(count));

		int countInt = StringToInt(count);

		ReplyToCommand(client, "Adding %i to count of %s.%s", countInt, type, name);
		AddThingCount(name, type, countInt);
	}
	else
	{
		ReplyToCommand(client, "Format: loot_add_thingcount [type] [name] [count]");
		ReplyToCommand(client, "Example: loot_add_thingcount weapon weapon_smg 2");
	}
	return Plugin_Handled;
}

Action Command_IsThingMaxed(int client, int args)
{
	if (args == 2)
	{
		char type[128], name[128];

		GetCmdArg(1, type, sizeof(type));
		GetCmdArg(2, name, sizeof(name));

		if (IsThingMaxReached(name, type))
			ReplyToCommand(client, "YES: %s.%s limit has been reached.", type, name);
		else
			ReplyToCommand(client, "NO: %s.%s limit has not been reached.", type, name);
	}
	else
	{
		ReplyToCommand(client, "Format: loot_thing_ismaxed [type] [name]");
		ReplyToCommand(client, "Example: loot_thing_ismaxed weapon weapon_smg");
	}
	return Plugin_Handled;
}

Action Command_GetThingMax(int client, int args)
{
	if (args == 2)
	{
		char type[128], name[128];

		GetCmdArg(1, type, sizeof(type));
		GetCmdArg(2, name, sizeof(name));

		ReplyToCommand(client, "Max allowed of %s.%s is %i", type, name, GetThingMax(name, type));
	}
	else
	{
		ReplyToCommand(client, "Format: loot_get_thingmax [type] [name]");
		ReplyToCommand(client, "Example: loot_get_thingmax weapon weapon_smg");
	}
	return Plugin_Handled;
}

//////////////////
// CVAR Related
///////////////////
void CvarOnOffChanged(ConVar convar, const char[] oldValue, const char[] newValue)
{
	g_bPluginOn = CVAR_loot_enabled.BoolValue;
}

void CvarLoggingChanged(ConVar convar, const char[] oldValue, const char[] newValue)
{
	g_bWriteLog = CVAR_loot_log_enabled.BoolValue;
}

void CvarConfigFileChanged(ConVar convar, const char[] oldValue, const char[] newValue)
{
	LoadConfig();
}

void CvarAnnounceModeChanged(ConVar convar, const char[] oldValue, const char[] newValue)
{
	g_iAnnounceMode = GetConVarInt(CVAR_loot_announce_mode);
}

///////////////////
// Events
///////////////////
Action Event_RoundStart(Event hEvent, const char[] strName, bool DontBroadcast)
{
	Log(false, "New round detected, reloading config.");
	LoadConfig();
	return Plugin_Continue;
}

Action Event_PlayerDeath(Event hEvent, const char[] strName, bool DontBroadcast)
{
	if (!g_bPluginOn || g_hConfig == null)
		return Plugin_Continue;

	char  victimTypeBuffer[48], victimType[48];
	float location[3];
	int	  clientId = GetClientOfUserId(hEvent.GetInt("userid"));
	if (clientId == 0)
	{
		// Something died but wasn't a player (bot or not) what was it?
		clientId = GetEventInt(hEvent, "entityid");
		GetEntityNetClass(clientId, victimTypeBuffer, sizeof(victimTypeBuffer));
		StrToLower(victimTypeBuffer, victimType, sizeof(victimType));
	}
	else
	{
		switch (GetEntProp(clientId, Prop_Send, "m_zombieClass"))
		{
			case ZC_SMOKER:
				victimType = "smoker";
			case ZC_BOOMER:
				victimType = "boomer";
			case ZC_HUNTER:
				victimType = "hunter";
			case ZC_SPITTER:
				victimType = "spitter";
			case ZC_JOCKEY:
				victimType = "jockey";
			case ZC_CHARGER:
				victimType = "charger";
			case ZC_TANK:
				victimType = "tank";
			case ZC_NOTINFECTED:
				return Plugin_Continue;
		}
	}

	GetEntPropVector(clientId, Prop_Send, "m_vecOrigin", location);

	InfectedKilled(victimType, false, location);

	if (StrEqual(victimType, "smoker", false) || StrEqual(victimType, "hunter", false) || StrEqual(victimType, "charger", false) || StrEqual(victimType, "boomer", false) || StrEqual(victimType, "jockey", false) || StrEqual(victimType, "spitter", false))
	{
		InfectedKilled("normal_infected", false, location);
	}
	else if (StrEqual(victimType, "tank", false) || StrEqual(victimType, "witch", false))
	{
		InfectedKilled("boss_infected", false, location);
	}

	InfectedKilled("global", false, location);

	return Plugin_Continue;
}

///////////////////
// Methods
///////////////////
void LoadConfig()
{
	if (g_hConfig != null)
	{
		CloseHandle(g_hConfig);
		g_hConfig = null;
	}

	g_hMaxSpawns		 = null;
	g_hMaxSpawnsCounters = null;

	g_hConfig			 = ConfigCreate();

	char fileName[256], fileNameCvar[256];

	CVAR_loot_cfg.GetString(fileNameCvar, sizeof(fileNameCvar));
	Format(fileName, sizeof(fileName), "cfg/sourcemod/%s", fileNameCvar);

	int errLine;
	if (!ConfigReadFile(g_hConfig, fileName, _, _, errLine))
	{
		LogError("Config file (%s) missing or has error on line %i", fileName, errLine);
		PrintToServer("Config file (%s) missing or has error on line %i", fileName, errLine);

		if (g_hConfig != null)
		{
			CloseHandle(g_hConfig);
			g_hConfig = null;
		}
	}
	else
	{
		// Loaded correctly, lets find\create sections.
		g_hMaxSpawns		 = ConfigLookup(g_hConfig, "max_spawns");
		g_hMaxSpawnsCounters = ConfigSettingAdd(ConfigRootSetting(g_hConfig), "max_spawns_counters", ST_Group);
	}
}

bool InfectedKilled(char[] infected, bool sim, float location[3])
{
	Log(sim, "Looking up class: %s", infected);
	Handle hClass = ConfigLookup(g_hConfig, infected);

	// If the class is defined in the drop settings.
	if (hClass != null)
	{
		bool   foundNormalThing = false, foundForcedThing = false;

		int	   thingRepeat = ConfigSettingGetMemberInt(hClass, "repeat");
		Handle hDieCount   = ConfigSettingGetMember(hClass, "dice");
		int	   dieCount	   = ConfigSettingLength(hDieCount);

		Log(sim, "Rolling for %i things", thingRepeat);

		// Loop the item count
		for (int thingCounter = 0; thingCounter < thingRepeat; thingCounter++)
		{
			Log(sim, "|-Rolling thing #%i", thingCounter + 1);
			int totalRoll = 0;

			// Roll each die
			Log(sim, "|--Rolling %i dice", dieCount);
			for (int dieCounter = 0; dieCounter < dieCount; dieCounter++)
			{
				int sides = ConfigSettingGetIntElement(hDieCount, dieCounter);
				int roll  = GetRandomInt(1, sides);
				totalRoll += roll;
				Log(sim, "|---Die #%i (%i sides) rolled %i", dieCounter + 1, sides, roll);
			}

			Log(sim, "|--Total roll: %i", totalRoll);

			// Done rolling, look for item to spawn
			char thingName[256], thingType[256];
			int	 thingSideMin = 0, thingSideMax = 0, nextIndex = 0;
			if (FindThing(hClass, totalRoll, nextIndex, thingName, thingType, thingSideMin, thingSideMax))
			{
				do
				{
					if (StrEqual(thingName, "weapon_pipebomb")) thingName = "weapon_pipe_bomb";	   // fix ture thingname
					Log(sim, "|--Thing found: %s with range of %i-%i", thingName, thingSideMin, thingSideMax);
					if (!IsThingMaxReached(thingName, thingType))
					{
						foundNormalThing = true;

						if (StrEqual(thingType, FACTORYNAME_ITEM, false))
						{
							Log(sim, "|---Sending to item factory.");
							ItemFactoryCreate(thingName, sim, location);
						}
						else if (StrEqual(thingType, FACTORYNAME_INFECTED, false))
						{
							Log(sim, "|---Sending to infected factory.");
							InfectedFactoryCreate(thingName, sim);
						}
						else if (StrEqual(thingType, FACTORYNAME_WEAPON, false))
						{
							Log(sim, "|---Sending to weapon factory.");
							WeaponFactoryCreate(thingName, sim, location);
						}
						else if (StrEqual(thingType, FACTORYNAME_UPGRADE, false))
						{
							Log(sim, "|---Sending to upgrade factory.");
							UpgradeFactoryCreate(thingName, sim, location);
						}
						else if (StrEqual(thingType, FACTORYNAME_MELEE, false))
						{
							Log(sim, "|---Sending to upgrade factory.");
							MeleeFactoryCreate(thingName, sim, location);
						}
						else if (StrEqual(thingType, FACTORYNAME_EXPLODE, false))
						{
							Log(sim, "|---Sending to explod factory.");
							ExplodeFactoryCreate(thingName, sim, location);
						}
					}
					else
						Log(sim, "|---Skipping factory, thing max reached.");
				}
				while (FindThing(hClass, totalRoll, nextIndex, thingName, thingType, thingSideMin, thingSideMax));
			}
			else
				Log(sim, "|--No thing found");
		}

		// Handle (if any) all things that don't have rolls. For example, when a tank dies, you could force a witch to spawn.
		foundForcedThing = ForcedThings(sim, hClass, location);

		if (foundForcedThing || foundNormalThing)
		{
			char   infectedNote[256], survivorNote[256];
			Handle hInfectedNote = ConfigSettingGetMember(hClass, "tell_infected");
			Handle hSurvivorNote = ConfigSettingGetMember(hClass, "tell_survivors");

			if (hInfectedNote != null)
				ConfigSettingGetString(hInfectedNote, infectedNote, sizeof(infectedNote));
			if (hSurvivorNote != null)
				ConfigSettingGetString(hSurvivorNote, survivorNote, sizeof(survivorNote));

			Announce(infectedNote, survivorNote);
		}
		return true;
	}
	else
		Log(sim, "Class not found");

	return false;
}

bool FindThing(Handle hClass, int rollAmount, int &NextIndex, char[] ThingName, char[] ThingType, int &ItemMin, int &ItemMax)
{
	if (hClass != null)
	{
		Handle hThings = ConfigSettingGetMember(hClass, "things");
		if (hThings != null)
		{
			int thingMax = ConfigSettingLength(hThings);

			for (int i = NextIndex; i < thingMax; i++)
			{
				Handle hThing = ConfigSettingGetElement(hThings, i);
				if (rollAmount >= ConfigSettingGetMemberInt(hThing, "min") && rollAmount <= ConfigSettingGetMemberInt(hThing, "max"))
				{
					ConfigSettingGetString(ConfigSettingGetMember(hThing, "name"), ThingName, 256);
					ConfigSettingGetString(ConfigSettingGetMember(hThing, "type"), ThingType, 256);
					ItemMin	  = ConfigSettingGetInt(ConfigSettingGetMember(hThing, "min"));
					ItemMax	  = ConfigSettingGetInt(ConfigSettingGetMember(hThing, "max"));
					NextIndex = i + 1;
					return true;
				}
			}
		}
	}
	return false;
}

bool ForcedThings(bool sim, Handle hClass, float location[3])
{
	bool returnValue = false;

	if (hClass != null)
	{
		Handle hThings = ConfigSettingGetMember(hClass, "things_no_roll");
		if (hThings != null)
		{
			int thingMax = ConfigSettingLength(hThings);
			Log(sim, "Forced thing count: %i", thingMax);

			for (int i = 0; i < thingMax; i++)
			{
				Handle hThing = ConfigSettingGetElement(hThings, i);
				char   thingName[256], thingType[256];

				ConfigSettingGetString(ConfigSettingGetMember(hThing, "name"), thingName, sizeof(thingName));
				ConfigSettingGetString(ConfigSettingGetMember(hThing, "type"), thingType, sizeof(thingType));

				if (StrEqual(thingName, "weapon_pipebomb")) thingName = "weapon_pipe_bomb";	   // fix ture thingname

				Log(sim, "|-Forcing thing #%i - %s", i + 1, thingName);

				if (!IsThingMaxReached(thingName, thingType))
				{
					if (StrEqual(thingType, FACTORYNAME_ITEM, false))
					{
						Log(sim, "|---Sending to item factory.");
						ItemFactoryCreate(thingName, sim, location);
					}
					else if (StrEqual(thingType, FACTORYNAME_INFECTED, false))
					{
						Log(sim, "|---Sending to infected factory.");
						InfectedFactoryCreate(thingName, sim);
					}
					else if (StrEqual(thingType, FACTORYNAME_WEAPON, false))
					{
						Log(sim, "|---Sending to weapon factory.");
						WeaponFactoryCreate(thingName, sim, location);
					}
					else if (StrEqual(thingType, FACTORYNAME_UPGRADE, false))
					{
						Log(sim, "|---Sending to upgrade factory.");
						UpgradeFactoryCreate(thingName, sim, location);
					}
					else if (StrEqual(thingType, FACTORYNAME_MELEE, false))
					{
						Log(sim, "|---Sending to upgrade factory.");
						MeleeFactoryCreate(thingName, sim, location);
					}
					else if (StrEqual(thingType, FACTORYNAME_EXPLODE, false))
					{
						Log(sim, "|---Sending to explod factory.");
						ExplodeFactoryCreate(thingName, sim, location);
					}

					returnValue = true;
				}
				else
					Log(sim, "|---Skipping factory, thing max reached.");
			}
		}
		else
			Log(sim, "Skipping forced things, does not exist.");
	}

	return returnValue;
}

/*void GiveItem(int client, const char[] itemName)
{
	int flags = GetCommandFlags("give");
	SetCommandFlags("give", flags & ~FCVAR_CHEAT);
	FakeClientCommand(client, "give %s", itemName);
	SetCommandFlags("give", flags);
}*/

void ClientCheatCommand(int client, const char[] command)
{
	int flags = GetCommandFlags(command);
	SetCommandFlags(command, flags & ~FCVAR_CHEAT);
	FakeClientCommand(client, command);
	SetCommandFlags(command, flags);
}

void SpawnInfected(const char[] name)
{
	Log(false, "zspawn %s", name);
	int flags = GetCommandFlags("z_spawn");
	SetCommandFlags("z_spawn", flags & ~FCVAR_CHEAT);
	FakeClientCommand(GetAnyClient(), "z_spawn %s", name);
	SetCommandFlags("z_spawn", flags);
}

void SpawnHorde(const char[] name)
{
	if (g_bSpawnUncommonSupported)
	{
		int flags = GetCommandFlags("sm_spawnuncommonhorde");
		SetCommandFlags("sm_spawnuncommonhorde", flags & ~ADMFLAG_CHEATS);
		FakeClientCommand(GetAnyClient(), "sm_spawnuncommonhorde %s", name);
		SetCommandFlags("sm_spawnuncommonhorde", flags);
	}
}

int SpawnItem(float location[3] = NULL_VECTOR, float angles[3] = NULL_VECTOR, float velocity[3] = NULL_VECTOR, const char[] name, const char[] model = MODEL_NONE, bool dontSpawn = false)
{
	int entity = CreateEntityByName(name);
	if (entity != -1)
	{
		if (StrEqual(model, MODEL_NONE) == false)
			SetEntityModel(entity, model);

		DispatchKeyValue(entity, "spawnflags", "1");

		if (!dontSpawn)
		{
			DispatchSpawn(entity);
			ActivateEntity(entity);
			TeleportEntity(entity, location, angles, velocity);
		}
	}
	return entity;
}

void SpawnItemFinish(int entity, float location[3] = NULL_VECTOR, float angles[3] = NULL_VECTOR, float velocity[3] = NULL_VECTOR)
{
	DispatchSpawn(entity);
	ActivateEntity(entity);
	// char weaponClass[64];
	// GetEdictClassname(entity, weaponClass, sizeof(weaponClass));
	// PrintToChatAll("teleport entity:%s on:x:%.2f y:%.2f z:%.2f", weaponClass, location[0], location[1], location[2]);	 //  halflife.inc
	TeleportEntity(entity, location, angles, velocity);
}

bool IsThingMaxReached(char[] name, char[] type)
{
	if (g_hMaxSpawns != null)
	{
		// Look up that thing and type. if 0 it was not found or set to 0 meaning don't max.
		int maxAmount = GetThingMax(name, type);

		// If -1, it's set to not allow.
		if (maxAmount == -1)
			return true;
		else if (maxAmount > 0)
		{
			// We have an amount, lets check for current
			return GetThingCount(name, type) >= maxAmount;
		}
	}

	return false;
}

int GetThingMax(char[] name, char[] type)
{
	if (g_hMaxSpawns != null)
	{
		char pathMax[256];
		Format(pathMax, sizeof(pathMax), "max_spawns.%s.%s", type, name);
		// Look up that thing and type. if 0 it was not found or set to 0 meaning don't max.
		return ConfigLookupInt(g_hConfig, pathMax);
	}
	return 0;
}

void AddThingCount(char[] name, char[] type, int countToAdd)
{
	if (g_hMaxSpawnsCounters != null)
	{
		Handle hThing;
		int	   thingCount = GetThingCount(name, type, hThing);

		if (hThing != null)
		{
			// Get the value, add one, return.
			ConfigSettingSetInt(hThing, thingCount + countToAdd);
		}
	}
}

int GetThingCount(char[] name, char[] type, Handle thing = null)
{
	if (g_hMaxSpawnsCounters != null)
	{
		// Find or create type
		Handle hType = ConfigSettingGetMember(g_hMaxSpawnsCounters, type);

		if (hType == null)
		{
			hType = ConfigSettingAdd(g_hMaxSpawnsCounters, type, ST_Group);

			if (hType == null)
			{
				Log(false, "Unable to create max_spawns_counters.%s", type);
				LogError("Unable to create max_spawns_counters.%s", type);
				thing = null;
				return 0;
			}
		}

		// Find or create thing
		thing = ConfigSettingGetMember(hType, name);

		if (thing == null)
		{
			thing = ConfigSettingAdd(hType, name, ST_Int);

			if (thing == null)
			{
				Log(false, "Unable to create max_spawns_counters.%s.%s", type, name);
				LogError("Unable to create max_spawns_counters.%s.%s", type, name);
				thing = null;
			}

			// Return here. We created it or didn't. Still return 0 and whatever the handle is.
			return 0;
		}

		// It exists already, so grab and return.
		return ConfigSettingGetInt(thing);
	}

	thing = null;
	return 0;
}

void Announce(char[] infectedText = NULL_STRING, char[] survivorText = NULL_STRING)
{
	if (g_iAnnounceMode != 0)
	{
		for (int i = 1; i <= MaxClients; i++)
		{
			if (IsClientInGame(i) && !IsFakeClient(i))
			{
				int team = GetClientTeam(i);

				if (!StrEqual(infectedText, NULL_STRING) && team == TEAM_INFECTED)
				{
					if (g_iAnnounceMode == 1)
					{
						PrintHintText(i, infectedText);
					}
					else if (g_iAnnounceMode == 2)
					{
						PrintToChat(i, infectedText);
					}
				}

				if (!StrEqual(survivorText, NULL_STRING) && team == TEAM_SURVIVOR)
				{
					if (g_iAnnounceMode == 1)
					{
						PrintHintText(i, survivorText);
					}
					else if (g_iAnnounceMode == 2)
					{
						PrintToChat(i, survivorText);
					}
				}
			}
		}
	}
}

///////////////////
// Helpers
///////////////////
int GetAnyClient()
{
	for (int i = 1; i <= MaxClients; i++)
	{
		if (IsClientInGame(i))
		{
			return i;
		}
	}
	return 0;
}

void Log(bool sim, const char[] format, any...)
{
	char newString[256];
	VFormat(newString, sizeof(newString), format, 3);

	if (sim)
	{
		PrintToChatAll(newString);
		PrintToServer(newString);
	}
	else if (g_bWriteLog)
	{
		LogMessage(newString);
		PrintToServer(newString);
	}
}

int ConfigSettingGetMemberInt(Handle setting, char[] name)
{
	Handle hMember = ConfigSettingGetMember(setting, name);
	if (hMember != null)
		return ConfigSettingGetInt(hMember);
	else
		return -1;
}

stock int StrToLower(const char[] str, char[] buffer, int bufsize)
{
	int n = 0, x = 0;
	while (str[n] != '\0' && x < (bufsize - 1))
	{							// Make sure we are inside bounds
		int Char = str[n++];	// Caching

		if (IsCharUpper(Char))
		{								 // Am I big ?
			Char = CharToLower(Char);	 // Big becomes low
		}

		buffer[x++] = Char;	   // Write into our new string
	}

	buffer[x++] = '\0';	   // Finalize with the end ( = always 0 for strings)

	return x;	 // return number of bytes written for later proove
}

///////////////////
// Factories
///////////////////
void ItemFactoryCreate(char[] itemName, bool sim, float location[3])
{
	Log(sim, "Item Factory Creating: %s", itemName);

	if (!sim)
	{
		// Mod location so it spawns around mid level of model.
		location[2] += 10.0;

		// Create random velocity
		float vel[3];
		vel[0] = GetRandomFloat(-80.0, 80.0);
		vel[1] = GetRandomFloat(-80.0, 80.0);
		vel[2] = GetRandomFloat(40.0, 80.0);

		SpawnItem(location, _, vel, itemName);
		// PrintToChatAll("Create entity:%s location: x:%.2f y:%.2f z:%.2f", itemName, location[0], location[1], location[2]);	//  halflife.inc
		AddThingCount(itemName, FACTORYNAME_ITEM, 1);
	}
}

void WeaponFactoryCreate(char[] name, bool sim, float location[3])
{
	Log(sim, "Weapon Factory Creating: %s", name);

	if (!sim)
	{
		int entity = SpawnItem(_, _, _, "weapon_spawn", _, true);

		// Mod location so it spawns around mid level of model.
		location[2] += 10.0;

		// Create random velocity
		float vel[3];
		vel[0] = GetRandomFloat(-80.0, 80.0);
		vel[1] = GetRandomFloat(-80.0, 80.0);
		vel[2] = GetRandomFloat(40.0, 80.0);
		// PrintToChatAll("set entity %s origin kv to x:%.2f y:%.2f z:%.2f", name, location[0], location[1], location[2]);  //  halflife.inc
		DispatchKeyValueVector(entity, "origin", location);
		DispatchKeyValue(entity, "weapon_selection", name);
		// PrintToChatAll("set weaopn_spawn to name(%s) %s ", name, DispatchKeyValue(entity, "weapon_selection", name) ? "ture" : "false");
		DispatchKeyValue(entity, "spawnflags", "1");
		DispatchKeyValue(entity, "solid", "6");
		DispatchKeyValue(entity, "count", "1");
		DispatchKeyValue(entity, "body", "0");
		DispatchKeyValue(entity, "spawn_without_director", "1");

		SpawnItemFinish(entity, _, _, vel);
		AddThingCount(name, FACTORYNAME_WEAPON, 1);
	}
}

void MeleeFactoryCreate(char[] name, bool sim, float location[3])
{
	Log(sim, "Melee Factory Creating: %s", name);

	if (!sim)
	{
		int entity = SpawnItem(_, _, _, "weapon_melee_spawn", _, true);

		// Mod location so it spawns around mid level of model.
		location[2] += 10.0;

		// Create random velocity
		float vel[3];
		vel[0] = GetRandomFloat(-80.0, 80.0);
		vel[1] = GetRandomFloat(-80.0, 80.0);
		vel[2] = GetRandomFloat(40.0, 80.0);

		DispatchKeyValueVector(entity, "origin", location);
		DispatchKeyValue(entity, "spawnflags", "1");
		DispatchKeyValue(entity, "solid", "6");
		DispatchKeyValue(entity, "count", "1");
		DispatchKeyValue(entity, "body", "0");
		DispatchKeyValue(entity, "melee_weapon", name);

		SpawnItemFinish(entity, _, _, vel);
		AddThingCount(name, FACTORYNAME_MELEE, 1);
	}
}

void UpgradeFactoryCreate(char[] name, bool sim, float location[3])
{
	Log(sim, "Upgrade Factory Creating: %s", name);

	if (!sim)
	{
		int entity = SpawnItem(_, _, _, "upgrade_spawn", _, true);

		// Mod location so it spawns around mid level of model.
		location[2] += 10.0;

		// Create random velocity
		float vel[3];
		vel[0] = GetRandomFloat(-80.0, 80.0);
		vel[1] = GetRandomFloat(-80.0, 80.0);
		vel[2] = GetRandomFloat(40.0, 80.0);

		DispatchKeyValueVector(entity, "origin", location);
		DispatchKeyValue(entity, "spawnflags", "1");

		// Do the individual upgrades
		if (StrContains(name, "laser", false) != -1)
		{
			DispatchKeyValue(entity, "laser_sight", "1");
			DispatchKeyValue(entity, "spawnflags", "2");
		}
		else
			DispatchKeyValue(entity, "laser_sight", "0");

		if (StrContains(name, "incendiary", false) != -1)
			DispatchKeyValue(entity, "upgradepack_incendiary", "1");
		else
			DispatchKeyValue(entity, "upgradepack_incendiary", "0");

		if (StrContains(name, "explosive", false) != -1)
			DispatchKeyValue(entity, "upgradepack_explosive", "1");
		else
			DispatchKeyValue(entity, "upgradepack_explosive", "0");

		SpawnItemFinish(entity, _, _, vel);
		AddThingCount(name, FACTORYNAME_UPGRADE, 1);
	}
}

void InfectedFactoryCreate(char[] name, bool sim, bool skipCount = false)
{
	Log(sim, "Infected Factory Creating: %s", name);

	if (!sim)
	{
		// Check for any special commands
		if (StrEqual(name, "panic", false))
		{
			ClientCheatCommand(GetAnyClient(), "director_force_panic_event");

			if (!skipCount)
				AddThingCount(name, FACTORYNAME_INFECTED, 1);
		}
		else if (StrContains(name, "mob-", false) != -1)
		{
			char parts[2][10];
			if (ExplodeString(name, "-", parts, 2, 10) > 1)
			{
				SpawnHorde(parts[1]);
			}

			if (!skipCount)
				AddThingCount(name, FACTORYNAME_INFECTED, 1);
		}
		else if (StrEqual(name, "infected-team", false))
		{
			InfectedFactoryCreate("boomer auto", sim, true);
			InfectedFactoryCreate("hunter auto", sim, true);
			InfectedFactoryCreate("smoker auto", sim, true);
			InfectedFactoryCreate("spitter auto", sim, true);
			InfectedFactoryCreate("jockey auto", sim, true);
			InfectedFactoryCreate("charger auto", sim, true);

			if (!skipCount)
				AddThingCount(name, FACTORYNAME_INFECTED, 1);
		}
		else if (StrEqual(name, "boss-team", false))
		{
			InfectedFactoryCreate("tank auto", sim, true);
			InfectedFactoryCreate("witch auto", sim, true);

			if (!skipCount)
				AddThingCount(name, FACTORYNAME_INFECTED, 1);
		}
		else
		{
			if (!skipCount)
				AddThingCount(name, FACTORYNAME_INFECTED, 1);

			ReplaceString(name, 256, "_", " ");

			SpawnInfected(name);
		}
	}
}

void ExplodeFactoryCreate(char[] name, bool sim, float location[3])
{
	Log(sim, "Weapon Factory Creating: %s", name);

	if (!sim)
	{
		int entity = CreateEntityByName("physics_prop");
		location[2] += 20.0;

		if (StrEqual(name, "weapon_fireworkcrate", false))
		{
			SetEntityModel(entity, "models/props_junk/explosive_box001.mdl");
		}
		else if (StrEqual(name, "weapon_gascan", false)) {
			SetEntityModel(entity, "models/props_junk/gascan001a.mdl");
		}
		else if (StrEqual(name, "weapon_propanetank", false)) {
			SetEntityModel(entity, "models/props_junk/propanecanister001a.mdl");
			int tankRef = EntIndexToEntRef(entity);
			g_PropaneTanks.Push(tankRef);
			CleanupDeadTanks();
		}
		else if (StrEqual(name, "weapon_oxygentank", false)) {
			SetEntityModel(entity, "models/props_equipment/oxygentank01.mdl");
		}
		DispatchKeyValue(entity, "spawnflags", "1");
		DispatchSpawn(entity);
		// ActivateEntity(entity);
		TeleportEntity(entity, location, NULL_VECTOR, NULL_VECTOR);
		//PrintToChatAll("teleport entity:%s on:x:%.2f y:%.2f z:%.2f", name, location[0], location[1], location[2]);
		AddThingCount(name, FACTORYNAME_EXPLODE, 1);
	}
}

public Action CH_PassFilter(int ent1, int ent2, bool &result)
{
	//PrintToChatAll("CH_PassFilter ent1:%d ent2:%d result:%s", ent1, ent2, result ? "true" : "false");
	if ((IsPlayer(ent1) && IsPropaneTank(ent2)) || (IsPlayer(ent2) && IsPropaneTank(ent1)))
	{
		//PrintToChatAll("try change ptank");
		result = false;
		return Plugin_Changed;
	}
	return Plugin_Continue;
}

stock void CleanupDeadTanks()
{
	for (int i = g_PropaneTanks.Length - 1; i >= 0; i--)
	{
		int entRef = g_PropaneTanks.Get(i);
		if (EntRefToEntIndex(entRef) == INVALID_ENT_REFERENCE)
		{
			g_PropaneTanks.Erase(i);
		}
	}
}

stock bool IsPropaneTank(int entity)
{
	CleanupDeadTanks();

	int len = g_PropaneTanks.Length;
	for (int i = 0; i < len; i++)
	{
		int tankRef = g_PropaneTanks.Get(i);
		int tankEnt = EntRefToEntIndex(tankRef);
		if (tankEnt == entity)
		{
			return true;
		}
	}
	return false;
}

bool IsPlayer(int entity)
{
	return entity > 0 && entity <= MaxClients && IsClientInGame(entity) && (GetClientTeam(entity) == 2);
}

public bool TraceFilter_IgnoreSelf(int entity, int contentsMask, any data)
{
	return entity != data;
}